[build-system]
requires = ["setuptools>=77", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "MIRTorch"
dynamic = ["version"]
authors = [{ name = "Guanhua Wang", email = "guanhuaw@umich.edu" }]
description = "a PyTorch-based image reconstruction toolbox"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["signal processing", "inverse problems"]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    'Development Status :: 2 - Pre-Alpha',
    'Topic :: Scientific/Engineering :: Image Processing',
]
dependencies = [
    "torch>=1.13",
    "torchvision",
    "torchkbnufft>=1.4.0",
    "finufft>=2.5,<3",
    "numpy>=1.24",
    "scipy",
    "PyWavelets",
]

[project.optional-dependencies]
examples = [
    "einops",
    "matplotlib",
]
finufft = [
    "finufft>=2.5,<3",
]
cufinufft = [
    "cufinufft>=2.5,<3",
]
test = [
    "coverage",
    "pytest",
]
dev = [
    "jupyterlab",
    "ipywidgets",
    "h5py",
    "gdown",
    "wget",
    "scikit-image",
    "scikit-learn",
    "einops",
    "matplotlib",
    "coverage",
    "pytest",
    "check-manifest",
    "pyright",
    "ruff",
]

[project.urls]
"repository" = "https://github.com/guanhuaw/MIRTorch"

[tool.ruff]
target-version = "py310"
exclude = [
    "__pycache__",
    ".github",
    ".idea",
    ".vscode",
    "build",
    "dist",
    "docs",
    "examples",
    "tests",
    "mirtorch/vendors/pytorch_wavelets",
    "venv",
    ".git",
]

[tool.setuptools_scm]

[tool.pyright]
include = [
    "mirtorch/alg",
    "mirtorch/linear/_finufft.py",
    "mirtorch/linear/linearmaps.py",
    "mirtorch/prox/prox.py",
]
exclude = [
    "__pycache__",
    ".github",
    ".idea",
    ".vscode",
    "build",
    "dist",
    "docs",
    "examples",
    "tests",
    "mirtorch/vendors/pytorch_wavelets",
    "venv",
    ".git",
]

[tool.semantic_release]
allow_zero_version = true
major_on_zero = false

[tool.pytest.ini_options]
python_files = "*_tests.py"
testpaths = ["tests"]

[tool.coverage.run]
source = ["mirtorch"]

[tool.coverage.report]
fail_under = 70
omit = ["mirtorch/vendors/*"]
